name: victorious
favicon: null
layout_spectrum: 0.34325
typography_spectrum: 0.8183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0920'
    - '#39354c'
    - '#a9a298'
    - '#625d59'
    - '#f9dbbf'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
